In [1]:
import numpy as np
#initailize the array
a= np.array([
    [100,200,150,300], #product1
    [50,60,40,80],     #product2
    [300,400,350,500], #product3
    [200,250,220,270], #product4
    [80,90,70,100]     #product5
])
a.size


20

In [2]:
a= np.array([
    [100,200,150,300], #product1
    [50,60,40,80],     #product2
    [300,400,350,500], #product3
    [200,250,220,270], #product4
    [80,90,70,100]     #product5
])
a.dtype


dtype('int32')

In [3]:
a= np.array([
    [100,200,150,300], #product1
    [50,60,40,80],     #product2
    [300,400,350,500], #product3
    [200,250,220,270], #product4
    [80,90,70,100]     #product5
])
a.itemsize



4

In [4]:
a= np.array([
    [100,200,150,300], #product1
    [50,60,40,80],     #product2
    [300,400,350,500], #product3
    [200,250,220,270], #product4
    [80,90,70,100]     #product5
])
a.sum()



3810

In [5]:
a= np.array([
    [100,200,150,300], #product1
    [50,60,40,80],     #product2
    [300,400,350,500], #product3
    [200,250,220,270], #product4
    [80,90,70,100]     #product5
])
a[2]-=10
print(a)


[[100 200 150 300]
 [ 50  60  40  80]
 [290 390 340 490]
 [200 250 220 270]
 [ 80  90  70 100]]


In [6]:

a= np.array([
    [100,200,150,300], #product1
    [50,60,40,80],     #product2
    [300,400,350,500], #product3
    [200,250,220,270], #product4
    [80,90,70,100]     #product5
])
a+=20
print(a)

[[120 220 170 320]
 [ 70  80  60 100]
 [320 420 370 520]
 [220 270 240 290]
 [100 110  90 120]]


In [7]:

a= np.array([
    [100,200,150,300], #product1
    [50,60,40,80],     #product2
    [300,400,350,500], #product3
    [200,250,220,270], #product4
    [80,90,70,100]     #product5
])
a[0:6,1]*=2
print(a)


[[100 400 150 300]
 [ 50 120  40  80]
 [300 800 350 500]
 [200 500 220 270]
 [ 80 180  70 100]]


In [8]:

a= np.array([
    [100,200,150,300], #product1
    [50,60,40,80],     #product2
    [300,400,350,500], #product3
    [200,250,220,270], #product4
    [80,90,70,100]     #product5
])
np.sum(a,axis=0)

array([ 730, 1000,  830, 1250])

In [9]:

a= np.array([
    [100,200,150,300], #product1
    [50,60,40,80],     #product2
    [300,400,350,500], #product3
    [200,250,220,270], #product4
    [80,90,70,100]     #product5
])
np.sum(a,axis=1)

array([ 750,  230, 1550,  940,  340])

In [10]:
a= np.array([
    [100,200,150,300], #product1
    [50,60,40,80],     #product2
    [300,400,350,500], #product3
    [200,250,220,270], #product4
    [80,90,70,100]     #product5
])
np.min(a,axis=1)


array([100,  40, 300, 200,  70])

In [11]:
a= np.array([
    [100,200,150,300], #product1
    [50,60,40,80],     #product2
    [300,400,350,500], #product3
    [200,250,220,270], #product4
    [80,90,70,100]     #product5
])
np.max(a,axis=0)


array([300, 400, 350, 500])

In [12]:
a= np.array([
    [100,200,150,300], #product1
    [50,60,40,80],     #product2
    [300,400,350,500], #product3
    [200,250,220,270], #product4
    [80,90,70,100]     #product5
])
np.mean(a,axis=1)



array([187.5,  57.5, 387.5, 235. ,  85. ])

In [13]:
a= np.array([
    [100,200,150,300], #product1
    [50,60,40,80],     #product2
    [300,400,350,500], #product3
    [200,250,220,270], #product4
    [80,90,70,100]     #product5
])
a[1]



array([50, 60, 40, 80])

In [14]:
a= np.array([
    [100,200,150,300], #product1
    [50,60,40,80],     #product2
    [300,400,350,500], #product3
    [200,250,220,270], #product4
    [80,90,70,100]     #product5
])
a[:,3]

array([300,  80, 500, 270, 100])

In [15]:
a= np.array([
    [100,200,150,300], #product1
    [50,60,40,80],     #product2
    [300,400,350,500], #product3
    [200,250,220,270], #product4
    [80,90,70,100]     #product5
])
a[0:3,0:2]

array([[100, 200],
       [ 50,  60],
       [300, 400]])

In [16]:
a= np.array([
    [100,200,150,300], #product1
    [50,60,40,80],     #product2
    [300,400,350,500], #product3
    [200,250,220,270], #product4
    [80,90,70,100]     #product5
])
a[3:6,2:4]

array([[220, 270],
       [ 70, 100]])

In [17]:
a= np.array([
    [100,200,150,300], #product1
    [50,60,40,80],     #product2
    [300,400,350,500], #product3
    [200,250,220,270], #product4
    [80,90,70,100]     #product5
])
a[4:6,3:4]

array([[100]])

In [18]:
a= np.array([
    [100,200,150,300], #product1
    [50,60,40,80],     #product2
    [300,400,350,500], #product3
    [200,250,220,270], #product4
    [80,90,70,100]     #product5
])
a[1,3]=100
print(a)

[[100 200 150 300]
 [ 50  60  40 100]
 [300 400 350 500]
 [200 250 220 270]
 [ 80  90  70 100]]


In [19]:
a= np.array([
    [100,200,150,300], #product1
    [50,60,40,80],     #product2
    [300,400,350,500], #product3
    [200,250,220,270], #product4
    [80,90,70,100]     #product5
])
a[0:0]
a[3,2]


220

In [20]:
a= np.array([
    [100,200,150,300], #product1
    [50,60,40,80],     #product2
    [300,400,350,500], #product3
    [200,250,220,270], #product4
    [80,90,70,100]     #product5
])
stock_level=a[[0,3],[0,2]]
stock_level


array([100, 220])

In [21]:
import pandas as pd
data = {
    "Location1": [100, 50, 300, 200, 80],
    "Location2": [200, 60, 400, 250, 90],
    "Location3": [150, 40, 350, 220, 70],
    "Location4": [300, 80, 500, 270, 100]
}
inventory = pd.DataFrame(data, index=["Product1", "Product2", "Product3", "Product4", "Product5"])


In [22]:
inventory.head(2)

,Location1,Location2,Location3,Location4
Product1,100,200,150,300
Product2,50,60,40,80


In [23]:
inventory.shape

(5, 4)

In [24]:
inventory.columns, inventory.index

(Index(['Location1', 'Location2', 'Location3', 'Location4'], dtype='object'),
 Index(['Product1', 'Product2', 'Product3', 'Product4', 'Product5'], dtype='object'))

In [25]:
inventory.dtypes


Location1    int64
Location2    int64
Location3    int64
Location4    int64
dtype: object

In [26]:
inventory.isnull().sum()


Location1    0
Location2    0
Location3    0
Location4    0
dtype: int64

In [27]:
inventory.loc["Product3"]

Location1    300
Location2    400
Location3    350
Location4    500
Name: Product3, dtype: int64

In [30]:
inventory["Location2"]


Product1    200
Product2     60
Product3    400
Product4    250
Product5     90
Name: Location2, dtype: int64

In [31]:
inventory.loc[["Product1", "Product4"], ["Location1", "Location3"]]


,Location1,Location3
Product1,100,150
Product4,200,220


In [32]:

inventory.iloc[:3, :2]

,Location1,Location2
Product1,100,200
Product2,50,60
Product3,300,400
